Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot '_assert.ps1')
$ErrorActionPreference = 'Stop'

# Blok UMS v instrukčním souboru (design 3.4): Set-MarkedBlock nahradí blok
# mezi markery na místě; v souboru bez markerů najde sekce podle nadpisu
# ($UmsOwnedHeadings), nahradí je blokem na místě první z nich a zbytek souboru
# nechá byte-identický. Get-MarkedBlockContent čte obsah bloku zpět.
# Sada píše jen do OS temp; živé monorepo se jí netýká.
. (Join-Path $PSScriptRoot '..\sync-with-monorepo.ps1') -DotSourceOnly

# Marker je smluvní řetězec (jiné nástroje ho hledají doslova) - záměrně
# opsaný jako literál, ne přečtený ze skriptu.
$begin = '<!-- UMS-MEMORY-BANK BEGIN (generated by ums/sync-with-monorepo.ps1 - edit ums/CLAUDE.md.sample instead) -->'
$end   = '<!-- UMS-MEMORY-BANK END -->'

$work = Join-Path ([IO.Path]::GetTempPath()) ("ums-sync-claudemd-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $work | Out-Null
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Write-Raw([string] $Name, [string] $Text) {
    $p = Join-Path $work $Name
    [IO.File]::WriteAllText($p, $Text, $utf8)
    return $p
}
function Read-Raw([string] $Path) { return [IO.File]::ReadAllText($Path, $utf8) }
function Get-Sha([string] $Path) { return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash }
function Count-Of([string] $Text, [string] $Needle) {
    return ([regex]::Matches($Text, [regex]::Escape($Needle))).Count
}

try {
    # --- konstanta vlastněných nadpisů --------------------------------------
    Assert-Eq (@($UmsOwnedHeadings).Count) 3 'UmsOwnedHeadings: tři nadpisy'
    Assert-Eq $UmsOwnedHeadings[0] '## Memory Bank contract' 'UmsOwnedHeadings[0]'
    Assert-Eq $UmsOwnedHeadings[1] '## Superpowers × Memory Bank (uživatelské preference)' 'UmsOwnedHeadings[1]'
    Assert-Eq $UmsOwnedHeadings[2] '## Zákaz git worktree' 'UmsOwnedHeadings[2]'

    # --- nový sample (pracovní strom): bez WF engine, SDD i Native ----------
    $samplePath = Join-Path $PSScriptRoot '..\CLAUDE.md.sample'
    $sample = (Read-Raw $samplePath) -replace "`r`n", "`n"
    Assert-True ($sample -cnotmatch 'WF engine') 'sample: sekce WF engine je pryč'
    Assert-True ($sample -cnotmatch 'KicWorkflow') 'sample: žádná zmínka KicWorkflow'
    Assert-True ($sample -cnotmatch 'wf-bpmn-authoring|wf-element-dev') 'sample: žádné WF skilly'
    Assert-Eq (Count-Of $sample '**Exekuce plánu (SDD i Native):**') 1 'sample: odrážka "Exekuce plánu (SDD i Native)" právě jednou'
    Assert-True ($sample -cnotmatch '\*\*Exekuce plánu \(SDD\):\*\*') 'sample: stará odrážka "Exekuce plánu (SDD)" pryč'
    foreach ($h in $UmsOwnedHeadings) {
        Assert-Eq (Count-Of $sample ("`n" + $h + "`n")) 1 "sample: nadpis '$h' právě jednou"
    }

    # --- (a) legacy soubor: migrace na místě --------------------------------
    $legacy = (Read-Raw (Join-Path $PSScriptRoot 'fixtures\claude-md-legacy.md')) -replace "`r`n", "`n"
    Assert-True ($legacy.Contains("`n## WF engine (KicWorkflow)")) '(a) fixtura: legacy má sekci WF engine'
    $wfStart = $legacy.IndexOf("`n## WF engine") + 1
    $wfSection = $legacy.Substring($wfStart)                     # WF engine je poslední sekce
    Assert-True ($wfSection.StartsWith('## WF engine')) '(a) fixtura: WF sekce vyříznuta od svého nadpisu'

    $f1 = Write-Raw 'legacy.md' $legacy
    Set-MarkedBlock $f1 $sample $UmsOwnedHeadings
    $r1 = Read-Raw $f1
    Assert-Eq (Count-Of $r1 $begin) 1 '(a) právě jeden BEGIN marker'
    Assert-Eq (Count-Of $r1 $end) 1 '(a) právě jeden END marker'
    Assert-Eq (Count-Of $r1 "`n## Memory Bank contract`n") 1 '(a) nadpis "## Memory Bank contract" právě jednou'
    Assert-Eq (Count-Of $r1 "`n## Zákaz git worktree`n") 1 '(a) nadpis "## Zákaz git worktree" právě jednou'
    Assert-True ($r1.StartsWith("# CLAUDE.md`n`n" + $begin + "`n")) '(a) titulek zůstal první, blok hned za ním na místě první vlastněné sekce'
    $iEnd = $r1.IndexOf($end)
    Assert-True ($r1.IndexOf('## WF engine') -gt $iEnd) '(a) sekce WF engine leží MIMO blok (za END)'
    Assert-True ($r1.EndsWith("`n`n" + $wfSection)) '(a) WF engine sekce je byte-identická a oddělená prázdným řádkem'
    $expected = "# CLAUDE.md`n`n" + $begin + "`n" + $sample.TrimEnd("`n") + "`n" + $end + "`n`n" + $wfSection
    Assert-True ($r1 -ceq $expected) '(a) celý výsledek = titulek + blok + nevlastněná sekce, nic dalšího'

    # (b) idempotence: druhé volání se stejným obsahem nezmění ani bajt
    $h1 = Get-Sha $f1
    Set-MarkedBlock $f1 $sample $UmsOwnedHeadings
    Assert-Eq (Get-Sha $f1) $h1 '(b) druhé volání: soubor byte-identický'
    # ... ani bez OwnedHeadings (marker cesta)
    Set-MarkedBlock $f1 $sample
    Assert-Eq (Get-Sha $f1) $h1 '(b) druhé volání bez OwnedHeadings: soubor byte-identický'

    # (c) Get-MarkedBlockContent: legacy soubor = tři vlastněné sekce bez WF engine
    $g = Get-MarkedBlockContent $f1 $UmsOwnedHeadings
    Assert-Eq $g ($sample.TrimEnd("`n")) '(c) migrovaný soubor: obsah bloku = sample'
    $legacyFile = Write-Raw 'legacy-read.md' $legacy
    $gl = Get-MarkedBlockContent $legacyFile $UmsOwnedHeadings
    foreach ($h in $UmsOwnedHeadings) {
        Assert-Eq (Count-Of ("`n" + $gl + "`n") ("`n" + $h + "`n")) 1 "(c) legacy: vlastněná sekce '$h' právě jednou"
    }
    Assert-True ($gl.StartsWith('## Memory Bank contract')) '(c) legacy: začíná první vlastněnou sekcí, ne titulkem'
    Assert-True ($gl -cnotmatch 'WF engine') '(c) legacy: bez sekce WF engine'
    Assert-True ($gl -cnotmatch '(?m)^# CLAUDE\.md') '(c) legacy: bez titulku souboru'
    $iFirst = $legacy.IndexOf('## Memory Bank contract')
    $iWf = $legacy.IndexOf('## WF engine')
    Assert-Eq $gl ($legacy.Substring($iFirst, $iWf - $iFirst).TrimEnd("`n")) '(c) legacy: tři sekce doslova ve pořadí souboru'
    Assert-Eq (Get-Sha $legacyFile) (Get-Sha (Write-Raw 'legacy-copy.md' $legacy)) '(c) čtení soubor nezměnilo'

    # (d) konce řádků se zachovávají: CRLF legacy -> CRLF výsledek, idempotentně
    $legacyCrlf = $legacy -replace "`n", "`r`n"
    $f2 = Write-Raw 'legacy-crlf.md' $legacyCrlf
    Set-MarkedBlock $f2 $sample $UmsOwnedHeadings
    $r2 = Read-Raw $f2
    Assert-True ($r2 -cnotmatch "(?<!`r)`n") '(d) CRLF vstup: ve výsledku žádný holý LF'
    Assert-True (($r2 -replace "`r`n", "`n") -ceq $expected) '(d) CRLF vstup: stejný obsah jako LF varianta'
    $h2 = Get-Sha $f2
    Set-MarkedBlock $f2 $sample $UmsOwnedHeadings
    Assert-Eq (Get-Sha $f2) $h2 '(d) CRLF: druhé volání byte-identické'
    Assert-Eq (Get-MarkedBlockContent $f2 $UmsOwnedHeadings) ($sample.TrimEnd("`n")) '(d) CRLF: obsah bloku se čte s LF'
    $gl2 = Get-MarkedBlockContent (Write-Raw 'legacy-crlf-read.md' $legacyCrlf) $UmsOwnedHeadings
    Assert-Eq $gl2 $gl '(d) CRLF legacy: vlastněné sekce se čtou stejně jako z LF'

    # (e) nesouvislé vlastněné sekce, přesné porovnání nadpisů, hranice sekce
    $mixed = @(
        '# CLAUDE.md', '',
        'Úvod projektu.', '',
        '## Memory Bank contract', 'stará první', '',
        '### Podsekce vlastněné sekce', 'zmizí spolu s ní', '',
        '## Projektová sekce A', 'zůstane', '',
        '## Superpowers × Memory Bank (uživatelské preference)   ', 'nadpis s koncovými mezerami', '',
        '## Zákaz git worktree extra', 'jiný nadpis, NENÍ vlastněný', '',
        '### Memory Bank contract', 'nižší úroveň, NENÍ vlastněný', '',
        '## memory bank contract', 'jiná velikost písmen, NENÍ vlastněný', '',
        '## Zákaz git worktree', 'stará třetí', '',
        '## Projektová sekce B', 'zůstane taky', ''
    ) -join "`n"
    $f3 = Write-Raw 'mixed.md' $mixed
    Set-MarkedBlock $f3 $sample $UmsOwnedHeadings
    $r3 = Read-Raw $f3
    $expected3 = @(
        '# CLAUDE.md', '',
        'Úvod projektu.', '',
        $begin, $sample.TrimEnd("`n"), $end, '',
        '## Projektová sekce A', 'zůstane', '',
        '## Zákaz git worktree extra', 'jiný nadpis, NENÍ vlastněný', '',
        '### Memory Bank contract', 'nižší úroveň, NENÍ vlastněný', '',
        '## memory bank contract', 'jiná velikost písmen, NENÍ vlastněný', '',
        '## Projektová sekce B', 'zůstane taky', ''
    ) -join "`n"
    Assert-True ($r3 -ceq $expected3) '(e) nesouvislé sekce: blok na místě první, ostatní vlastněné pryč, cizí (i podobné) nadpisy beze změny'
    Assert-True ($r3 -cnotmatch 'zmizí spolu s ní') '(e) podsekce ### vlastněné sekce zmizela s ní'
    $gm = Get-MarkedBlockContent (Write-Raw 'mixed-read.md' $mixed) $UmsOwnedHeadings
    Assert-True ($gm.StartsWith("## Memory Bank contract`nstará první`n")) '(e) čtení: první vlastněná sekce s podsekcí'
    Assert-True ($gm.Contains("`n### Podsekce vlastněné sekce`n")) '(e) čtení: podsekce je součástí sekce'
    Assert-True ($gm.Contains("`n## Superpowers × Memory Bank (uživatelské preference)   `nnadpis s koncovými mezerami`n")) '(e) čtení: nadpis s koncovými mezerami se pozná a vrací se doslova'
    Assert-True ($gm.EndsWith("stará třetí")) '(e) čtení: končí třetí vlastněnou sekcí'
    Assert-True ($gm -cnotmatch 'Projektová sekce') '(e) čtení: projektové sekce mezi vlastněnými nejsou'
    Assert-True ($gm -cnotmatch 'NENÍ vlastněný') '(e) čtení: podobné nadpisy nejsou'

    # (f) vlastněná sekce na konci souboru bez koncového newline; poslední sekce pryč
    $tail = "# CLAUDE.md`n`n## Memory Bank contract`nprvní`n`n## Projekt`nX`n`n## Zákaz git worktree`nposlední bez newline"
    $f4 = Write-Raw 'tail.md' $tail
    Set-MarkedBlock $f4 $sample $UmsOwnedHeadings
    $r4 = Read-Raw $f4
    $expected4 = "# CLAUDE.md`n`n" + $begin + "`n" + $sample.TrimEnd("`n") + "`n" + $end + "`n`n## Projekt`nX`n"
    Assert-Eq $r4 $expected4 '(f) odstraněná vlastněná sekce na konci nenechá viset prázdné řádky'
    $h4 = Get-Sha $f4
    Set-MarkedBlock $f4 $sample $UmsOwnedHeadings
    Assert-Eq (Get-Sha $f4) $h4 '(f) idempotence'

    # (g) dnešní chování zůstává: s markery bez OwnedHeadings nahradí na místě,
    #     bez markerů a bez vlastněných sekcí připojí na konec, chybějící soubor vznikne
    $withMarkers = "Před`n`n" + $begin + "`nstarý obsah`n" + $end + "`n`nZa`n"
    $f5 = Write-Raw 'markers.md' $withMarkers
    Set-MarkedBlock $f5 'nový obsah'
    Assert-Eq (Read-Raw $f5) ("Před`n`n" + $begin + "`nnový obsah`n" + $end + "`n`nZa`n") '(g) markery: blok nahrazen na místě'
    $foreign = "# AGENTS.md`n`n## Cizí sekce`nA`n"
    $f6 = Write-Raw 'foreign.md' $foreign
    Set-MarkedBlock $f6 'obsah' $UmsOwnedHeadings
    Assert-Eq (Read-Raw $f6) ($foreign.TrimEnd("`n") + "`n`n" + $begin + "`nobsah`n" + $end + "`n") '(g) bez markerů a bez vlastněných sekcí: připojeno na konec'
    $f7 = Write-Raw 'foreign2.md' $foreign
    Set-MarkedBlock $f7 'obsah'
    Assert-Eq (Read-Raw $f7) (Read-Raw $f6) '(g) bez OwnedHeadings: totéž jako s vlastněnými nadpisy, které v souboru nejsou'
    $f8 = Join-Path $work 'sub\new.md'
    Set-MarkedBlock $f8 'nový' $UmsOwnedHeadings
    Assert-Eq (Read-Raw $f8) ($begin + "`nnový`n" + $end + "`n") '(g) chybějící soubor vznikne jen s blokem'
    $threw = $false
    $f9 = Write-Raw 'corrupt.md' ("x`n" + $begin + "`nbez konce`n")
    try { Set-MarkedBlock $f9 'a' $UmsOwnedHeadings } catch { $threw = $true }
    Assert-True $threw '(g) poškozené markery: výjimka'

    # (h) Get-MarkedBlockContent: nic nenalezeno -> $null
    Assert-True ($null -eq (Get-MarkedBlockContent (Join-Path $work 'neexistuje.md') $UmsOwnedHeadings)) '(h) chybějící soubor: $null'
    $f10 = Write-Raw 'plain.md' "# X`n`n## Nic`ntext`n"
    Assert-True ($null -eq (Get-MarkedBlockContent $f10 $UmsOwnedHeadings)) '(h) bez markerů a bez vlastněných sekcí: $null'
    Assert-True ($null -eq (Get-MarkedBlockContent (Write-Raw 'legacy-noheadings.md' $legacy) @())) '(h) bez markerů a bez OwnedHeadings: $null i u legacy souboru'
    Assert-True ($null -eq (Get-MarkedBlockContent (Write-Raw 'legacy-noheadings2.md' $legacy))) '(h) OwnedHeadings vynechané: $null'
    $threw = $false
    try { $null = Get-MarkedBlockContent $f9 $UmsOwnedHeadings } catch { $threw = $true }
    Assert-True $threw '(h) poškozené markery: výjimka i při čtení'
}
finally {
    Remove-Item -LiteralPath $work -Recurse -Force -ErrorAction SilentlyContinue
}

Complete-Tests
